[2025-03-12 13:11:29,762:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-12 13:11:29,772:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-12 13:11:55,150:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-12 13:11:55,152:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-12 13:13:51,611:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-12 13:13:51,613:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-12 13:14:45,024:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-12 13:14:45,047:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-12 13:14:45,049:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-12 13:14:45,050:INFO: common:created directory at: artifacts]
[2025-03-12 13:14:45,052:INFO: common:created directory at: artifacts/data_ingestion]
[2025-03-12 13:17:07,543:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-12 13:17:07,545:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-12 13:17:07,546:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-12 13:17:07,547:INFO: common:created directory at: artifacts]
[2025-03-12 13:17:07,549:INFO: common:created directory at: artifacts/data_ingestion]
[2025-03-12 13:17:54,432:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-12 13:17:54,434:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-12 13:17:54,435:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-12 13:17:54,437:INFO: common:created directory at: artifacts]
[2025-03-12 13:17:54,438:INFO: common:created directory at: artifacts/data_ingestion]
[2025-03-12 13:17:55,370:INFO: 832124254:artifacts/data_ingestion/data.zip downloaded! with following info: 
Connection: close
Content-Length: 26176
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "f751ec0917e15a3dc07c3094a49fb99713109dd8a9f29150bb5d187ec17facdf"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 4942:110CCC:F8D89:281E31:67D13C2C
Accept-Ranges: bytes
Date: Wed, 12 Mar 2025 07:47:56 GMT
Via: 1.1 varnish
X-Served-By: cache-del21747-DEL
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1741765676.217021,VS0,VE292
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: ce965e741e8f5f2d924644c46630e312200ad781
Expires: Wed, 12 Mar 2025 07:52:56 GMT
Source-Age: 0

]
[2025-03-12 13:26:47,919:INFO: stage01_data_ingestion:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-12 13:26:47,922:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-12 13:26:47,922:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-12 13:26:47,922:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-12 13:26:47,922:INFO: common:created directory at: artifacts]
[2025-03-12 13:26:47,922:INFO: common:created directory at: artifacts/data_ingestion]
[2025-03-12 13:26:47,922:ERROR: stage01_data_ingestion:'DataIngestion' object has no attribute 'download_file']
Traceback (most recent call last):
  File "d:\KC\End to End MLflow\src\mlproject\pipeline\stage01_data_ingestion.py", line 26, in <module>
    obj.main()
  File "d:\KC\End to End MLflow\src\mlproject\pipeline\stage01_data_ingestion.py", line 17, in main
    data_ingestion.download_file()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataIngestion' object has no attribute 'download_file'
[2025-03-12 13:28:19,152:INFO: stage01_data_ingestion:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-12 13:28:19,152:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-12 13:28:19,152:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-12 13:28:19,152:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-12 13:28:19,166:INFO: common:created directory at: artifacts]
[2025-03-12 13:28:19,166:INFO: common:created directory at: artifacts/data_ingestion]
[2025-03-12 13:28:19,166:ERROR: stage01_data_ingestion:'DataIngestion' object has no attribute 'download_file']
Traceback (most recent call last):
  File "d:\KC\End to End MLflow\src\mlproject\pipeline\stage01_data_ingestion.py", line 26, in <module>
    obj.main()
  File "d:\KC\End to End MLflow\src\mlproject\pipeline\stage01_data_ingestion.py", line 17, in main
    data_ingestion.download_file()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataIngestion' object has no attribute 'download_file'
[2025-03-12 13:31:53,877:INFO: main:Welcome to our custom login]
[2025-03-12 13:31:54,139:INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-12 13:31:54,141:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-12 13:31:54,142:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-12 13:31:54,143:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-12 13:31:54,143:INFO: common:created directory at: artifacts]
[2025-03-12 13:31:54,143:INFO: common:created directory at: artifacts/data_ingestion]
[2025-03-12 13:31:54,144:ERROR: main:'DataIngestion' object has no attribute 'download_file']
Traceback (most recent call last):
  File "d:\KC\End to End MLflow\main.py", line 10, in <module>
    data_ingestion.main()
  File "d:\kc\end to end mlflow\src\mlproject\pipeline\stage01_data_ingestion.py", line 17, in main
    data_ingestion.download_file()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataIngestion' object has no attribute 'download_file'
[2025-03-12 13:34:27,560:INFO: stage01_data_ingestion:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-12 13:34:27,562:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-12 13:34:27,562:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-12 13:34:27,563:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-12 13:34:27,563:INFO: common:created directory at: artifacts]
[2025-03-12 13:34:27,564:INFO: common:created directory at: artifacts/data_ingestion]
[2025-03-12 13:34:27,564:ERROR: stage01_data_ingestion:'DataIngestion' object has no attribute 'download_file']
Traceback (most recent call last):
  File "d:\KC\End to End MLflow\src\mlproject\pipeline\stage01_data_ingestion.py", line 26, in <module>
    obj.main()
  File "d:\KC\End to End MLflow\src\mlproject\pipeline\stage01_data_ingestion.py", line 17, in main
    data_ingestion.download_file()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataIngestion' object has no attribute 'download_file'
[2025-03-12 13:36:26,125:INFO: stage01_data_ingestion:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-12 13:36:26,125:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-12 13:36:26,135:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-12 13:36:26,138:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-12 13:36:26,139:INFO: common:created directory at: artifacts]
[2025-03-12 13:36:26,139:INFO: common:created directory at: artifacts/data_ingestion]
[2025-03-12 13:36:26,972:INFO: data_ingestion:artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 26176
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "f751ec0917e15a3dc07c3094a49fb99713109dd8a9f29150bb5d187ec17facdf"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 4942:110CCC:F8D89:281E31:67D13C2C
Accept-Ranges: bytes
Date: Wed, 12 Mar 2025 08:06:28 GMT
Via: 1.1 varnish
X-Served-By: cache-del21730-DEL
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1741766788.838242,VS0,VE289
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 50ab5bae05008aa6183b91b79b771a42c1a67810
Expires: Wed, 12 Mar 2025 08:11:28 GMT
Source-Age: 0

]
[2025-03-12 13:36:26,994:INFO: stage01_data_ingestion:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-12 13:36:53,665:INFO: main:Welcome to our custom login]
[2025-03-12 13:36:53,924:INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-12 13:36:53,925:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-12 13:36:53,926:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-12 13:36:53,927:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-12 13:36:53,928:INFO: common:created directory at: artifacts]
[2025-03-12 13:36:53,928:INFO: common:created directory at: artifacts/data_ingestion]
[2025-03-12 13:36:54,106:INFO: data_ingestion:artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 26176
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "f751ec0917e15a3dc07c3094a49fb99713109dd8a9f29150bb5d187ec17facdf"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 4942:110CCC:F8D89:281E31:67D13C2C
Accept-Ranges: bytes
Date: Wed, 12 Mar 2025 08:06:55 GMT
Via: 1.1 varnish
X-Served-By: cache-del21733-DEL
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1741766815.294202,VS0,VE1
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: dbe880c00793081e5af411de16d1c26af39f328c
Expires: Wed, 12 Mar 2025 08:11:55 GMT
Source-Age: 27

]
[2025-03-12 13:36:54,120:INFO: main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 01:01:40,361:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-14 01:01:40,370:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-14 01:01:40,379:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-14 01:04:13,885:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-14 01:04:13,886:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-14 01:04:13,886:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-14 01:09:08,150:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-14 01:09:08,154:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-14 01:09:08,156:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-14 01:11:04,828:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-14 01:11:04,844:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-14 01:11:04,845:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-14 01:13:53,819:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-14 01:13:53,822:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-14 01:13:53,837:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-14 01:13:57,678:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-14 01:13:57,678:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-14 01:13:57,684:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-14 01:34:32,736:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-14 01:34:32,737:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-14 01:34:32,740:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-14 01:34:32,742:INFO: common:created directory at: artifacts]
[2025-03-14 01:34:32,744:INFO: common:created directory at: artifacts/data_validation]
[2025-03-14 01:39:09,446:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-14 01:39:09,448:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-14 01:39:09,450:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-14 01:39:09,452:INFO: common:created directory at: artifacts]
[2025-03-14 01:39:09,453:INFO: common:created directory at: artifacts/data_validation]
[2025-03-14 01:44:02,198:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-14 01:44:02,201:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-14 01:44:02,202:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-14 01:44:02,204:INFO: common:created directory at: artifacts]
[2025-03-14 01:44:02,205:INFO: common:created directory at: artifacts/data_validation]
[2025-03-14 13:09:44,804:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-14 13:09:44,810:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-14 13:09:44,814:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-14 13:09:44,816:INFO: common:created directory at: artifacts]
[2025-03-14 13:09:44,816:INFO: common:created directory at: artifacts/data_validation]
[2025-03-14 13:13:04,069:INFO: common:created directory at: artifacts/data_validation]
[2025-03-14 20:08:53,772:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-14 20:08:53,779:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-14 20:08:53,784:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-14 20:08:53,787:INFO: common:created directory at: artifacts]
[2025-03-14 20:08:53,789:INFO: common:created directory at: artifacts/data_validation]
[2025-03-15 00:32:19,369:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 00:32:19,379:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 00:32:19,385:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 00:32:19,393:INFO: common:created directory at: artifacts]
[2025-03-15 00:32:19,394:INFO: common:created directory at: artifacts/data_validation_new]
[2025-03-15 00:58:38,432:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 00:58:38,444:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 00:58:38,453:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 00:58:38,460:INFO: common:created directory at: artifacts]
[2025-03-15 00:58:38,462:INFO: common:created directory at: artifacts/data_validation_new]
[2025-03-15 01:00:23,308:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 01:00:23,312:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 01:00:23,312:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 01:00:23,312:INFO: common:created directory at: artifacts]
[2025-03-15 01:00:23,312:INFO: common:created directory at: artifacts/data_validation]
[2025-03-15 01:33:55,038:INFO: main:Welcome to our custom login]
[2025-03-15 01:33:55,038:INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-15 01:33:55,038:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 01:33:55,038:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 01:33:55,038:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 01:33:55,038:INFO: common:created directory at: artifacts]
[2025-03-15 01:33:55,047:INFO: common:created directory at: artifacts/data_ingestion]
[2025-03-15 01:33:56,182:INFO: data_ingestion:artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 26176
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "f751ec0917e15a3dc07c3094a49fb99713109dd8a9f29150bb5d187ec17facdf"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 3AAB:110CCC:44DC03:AD0040:67D48BAC
Accept-Ranges: bytes
Date: Fri, 14 Mar 2025 20:03:57 GMT
Via: 1.1 varnish
X-Served-By: cache-del21744-DEL
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1741982637.725230,VS0,VE523
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 118ac20c95438c788d247a17c93afd3715f32514
Expires: Fri, 14 Mar 2025 20:08:57 GMT
Source-Age: 0

]
[2025-03-15 01:33:56,208:INFO: main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-15 01:33:56,208:INFO: main:>>>>>> stage Data Validation stage started <<<<<<]
[2025-03-15 01:33:56,208:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 01:33:56,208:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 01:33:56,212:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 01:33:56,213:INFO: common:created directory at: artifacts]
[2025-03-15 01:33:56,213:ERROR: main:'ConfigurationManager' object has no attribute 'get_data_validation_config']
Traceback (most recent call last):
  File "d:\KC\End to End MLflow\main.py", line 22, in <module>
    data_ingestion.main()
  File "d:\kc\end to end mlflow\src\mlproject\pipeline\stage02_data_validation.py", line 14, in main
    data_validation_config = config.get_data_validation_config()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigurationManager' object has no attribute 'get_data_validation_config'. Did you mean: 'get_data_ingestion_config'?
[2025-03-15 01:39:44,822:INFO: main:Welcome to our custom login]
[2025-03-15 01:39:44,822:INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-15 01:39:44,824:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 01:39:44,824:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 01:39:44,824:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 01:39:44,824:INFO: common:created directory at: artifacts]
[2025-03-15 01:39:44,824:INFO: common:created directory at: artifacts/data_ingestion]
[2025-03-15 01:39:44,824:INFO: data_ingestion:File already exists of size: ~ 26 KB]
[2025-03-15 01:39:44,831:INFO: main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-15 01:39:44,831:INFO: main:>>>>>> stage Data Validation stage started <<<<<<]
[2025-03-15 01:39:44,834:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 01:39:44,835:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 01:39:44,838:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 01:39:44,838:INFO: common:created directory at: artifacts]
[2025-03-15 01:39:44,838:ERROR: main:'ConfigurationManager' object has no attribute 'get_data_validation_config']
Traceback (most recent call last):
  File "D:\KC\End to End MLflow\main.py", line 22, in <module>
    data_ingestion.main()
  File "d:\kc\end to end mlflow\src\mlproject\pipeline\stage02_data_validation.py", line 14, in main
    data_validation_config = config.get_data_validation_config()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigurationManager' object has no attribute 'get_data_validation_config'. Did you mean: 'get_data_ingestion_config'?
[2025-03-15 01:40:30,938:INFO: main:Welcome to our custom login]
[2025-03-15 01:40:30,938:INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-15 01:40:30,938:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 01:40:30,938:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 01:40:30,938:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 01:40:30,938:INFO: common:created directory at: artifacts]
[2025-03-15 01:40:30,938:INFO: common:created directory at: artifacts/data_ingestion]
[2025-03-15 01:40:30,938:INFO: data_ingestion:File already exists of size: ~ 26 KB]
[2025-03-15 01:40:30,948:INFO: main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-15 01:40:30,948:INFO: main:>>>>>> stage Data Validation stage started <<<<<<]
[2025-03-15 01:40:30,952:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 01:40:30,952:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 01:40:30,956:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 01:40:30,956:INFO: common:created directory at: artifacts]
[2025-03-15 01:40:30,956:ERROR: main:'ConfigurationManager' object has no attribute 'get_data_validation_config']
Traceback (most recent call last):
  File "d:\KC\End to End MLflow\main.py", line 22, in <module>
    data_ingestion.main()
  File "d:\kc\end to end mlflow\src\mlproject\pipeline\stage02_data_validation.py", line 14, in main
    data_validation_config = config.get_data_validation_config()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigurationManager' object has no attribute 'get_data_validation_config'. Did you mean: 'get_data_ingestion_config'?
[2025-03-15 11:22:00,316:INFO: main:Welcome to our custom login]
[2025-03-15 11:22:00,324:INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-15 11:22:00,344:ERROR: main:while scanning a simple key
  in "config\config.yaml", line 16, column 3
could not find expected ':'
  in "config\config.yaml", line 17, column 3]
Traceback (most recent call last):
  File "d:\KC\End to End MLflow\main.py", line 12, in <module>
    data_ingestion.main()
  File "d:\kc\end to end mlflow\src\mlproject\pipeline\stage01_data_ingestion.py", line 14, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "d:\kc\end to end mlflow\src\mlproject\config\configuration.py", line 13, in __init__
    self.config = read_yaml(config_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\kc\end to end mlflow\src\mlproject\utils\common.py", line 36, in read_yaml
    raise e
  File "d:\kc\end to end mlflow\src\mlproject\utils\common.py", line 30, in read_yaml
    content = yaml.safe_load(yaml_file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\scanner.py", line 115, in check_token
    while self.need_more_tokens():
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "config\config.yaml", line 16, column 3
could not find expected ':'
  in "config\config.yaml", line 17, column 3
[2025-03-15 11:23:34,967:INFO: main:Welcome to our custom login]
[2025-03-15 11:23:34,967:INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-15 11:23:34,971:ERROR: main:while scanning a simple key
  in "config\config.yaml", line 16, column 3
could not find expected ':'
  in "config\config.yaml", line 17, column 3]
Traceback (most recent call last):
  File "d:\KC\End to End MLflow\main.py", line 12, in <module>
    data_ingestion.main()
  File "d:\kc\end to end mlflow\src\mlproject\pipeline\stage01_data_ingestion.py", line 14, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "d:\kc\end to end mlflow\src\mlproject\config\configuration.py", line 13, in __init__
    self.config = read_yaml(config_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\kc\end to end mlflow\src\mlproject\utils\common.py", line 36, in read_yaml
    raise e
  File "d:\kc\end to end mlflow\src\mlproject\utils\common.py", line 30, in read_yaml
    content = yaml.safe_load(yaml_file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\scanner.py", line 115, in check_token
    while self.need_more_tokens():
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "config\config.yaml", line 16, column 3
could not find expected ':'
  in "config\config.yaml", line 17, column 3
[2025-03-15 11:26:08,014:INFO: main:Welcome to our custom login]
[2025-03-15 11:26:08,014:INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-15 11:26:08,048:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 11:26:08,050:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 11:26:08,053:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 11:26:08,053:INFO: common:created directory at: artifacts]
[2025-03-15 11:26:08,056:INFO: common:created directory at: artifacts/data_ingestion]
[2025-03-15 11:26:08,056:INFO: data_ingestion:File already exists of size: ~ 26 KB]
[2025-03-15 11:26:08,063:INFO: main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-15 11:26:08,063:INFO: main:>>>>>> stage Data Validation stage started <<<<<<]
[2025-03-15 11:26:08,063:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 11:26:08,067:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 11:26:08,067:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 11:26:08,071:INFO: common:created directory at: artifacts]
[2025-03-15 11:26:08,073:INFO: common:created directory at: artifacts/data_validation]
[2025-03-15 11:26:08,141:INFO: main:>>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-15 14:12:37,906:INFO: main:Welcome to our custom login]
[2025-03-15 14:12:37,906:INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-15 14:12:37,929:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 14:12:37,931:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 14:12:37,933:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 14:12:37,936:INFO: common:created directory at: artifacts]
[2025-03-15 14:12:37,937:INFO: common:created directory at: artifacts/data_ingestion]
[2025-03-15 14:12:38,945:INFO: data_ingestion:artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 26176
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "f751ec0917e15a3dc07c3094a49fb99713109dd8a9f29150bb5d187ec17facdf"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: BDE3:BC046:5CBBD:1060CF:67D53D7D
Accept-Ranges: bytes
Date: Sat, 15 Mar 2025 08:42:40 GMT
Via: 1.1 varnish
X-Served-By: cache-del21720-DEL
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1742028160.335544,VS0,VE511
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: b49d093510e6132e306ff8ae08669de7ca3a1ec9
Expires: Sat, 15 Mar 2025 08:47:40 GMT
Source-Age: 0

]
[2025-03-15 14:12:38,964:INFO: main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-15 14:12:38,966:INFO: main:>>>>>> stage Data Validation stage started <<<<<<]
[2025-03-15 14:12:38,966:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 14:12:38,968:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 14:12:38,969:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 14:12:38,971:INFO: common:created directory at: artifacts]
[2025-03-15 14:12:38,972:INFO: common:created directory at: artifacts/data_validation]
[2025-03-15 14:12:39,007:INFO: main:>>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-15 14:12:39,007:INFO: main:>>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-15 14:12:39,024:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 14:12:39,024:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 14:12:39,024:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 14:12:39,030:INFO: common:created directory at: artifacts]
[2025-03-15 14:12:39,030:INFO: common:created directory at: artifacts/data_transformation]
[2025-03-15 14:12:39,030:INFO: main:>>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-15 14:56:52,162:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 14:56:52,181:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 14:56:52,190:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 14:56:52,193:INFO: common:created directory at: artifacts]
[2025-03-15 15:05:27,995:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 15:05:28,012:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 15:07:08,907:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 15:07:08,909:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 15:07:08,918:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 15:07:08,918:INFO: common:created directory at: artifacts]
[2025-03-15 15:11:26,707:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 15:11:26,711:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 15:11:26,711:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 15:11:26,711:INFO: common:created directory at: artifacts]
[2025-03-15 15:11:26,711:INFO: common:created directory at: artifacts/model_trainer]
[2025-03-15 15:12:34,798:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 15:12:34,800:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 15:12:34,803:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 15:12:34,803:INFO: common:created directory at: artifacts]
[2025-03-15 15:12:34,803:INFO: common:created directory at: artifacts/model_trainer]
[2025-03-15 15:27:47,928:INFO: main:Welcome to our custom login]
[2025-03-15 15:27:47,928:INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-15 15:27:47,958:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 15:27:47,963:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 15:27:47,963:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 15:27:47,963:INFO: common:created directory at: artifacts]
[2025-03-15 15:27:47,963:INFO: common:created directory at: artifacts/data_ingestion]
[2025-03-15 15:27:47,963:INFO: data_ingestion:File already exists of size: ~ 26 KB]
[2025-03-15 15:27:47,997:INFO: main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-15 15:27:47,997:INFO: main:>>>>>> stage Data Validation stage started <<<<<<]
[2025-03-15 15:27:47,997:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 15:27:47,997:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 15:27:47,997:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 15:27:48,006:INFO: common:created directory at: artifacts]
[2025-03-15 15:27:48,006:INFO: common:created directory at: artifacts/data_validation]
[2025-03-15 15:27:48,053:INFO: main:>>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-15 15:27:48,053:INFO: main:>>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-15 15:27:48,075:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 15:27:48,075:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 15:27:48,080:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 15:27:48,080:INFO: common:created directory at: artifacts]
[2025-03-15 15:27:48,080:INFO: common:created directory at: artifacts/data_transformation]
[2025-03-15 15:27:48,080:INFO: main:>>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-15 15:29:54,843:INFO: main:Welcome to our custom login]
[2025-03-15 15:29:54,843:INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-15 15:29:54,843:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 15:29:54,843:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 15:29:54,843:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 15:29:54,843:INFO: common:created directory at: artifacts]
[2025-03-15 15:29:54,843:INFO: common:created directory at: artifacts/data_ingestion]
[2025-03-15 15:29:55,884:INFO: data_ingestion:artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 26176
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "f751ec0917e15a3dc07c3094a49fb99713109dd8a9f29150bb5d187ec17facdf"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 9EAE:2F9996:6EB14:133469:67D54F9C
Accept-Ranges: bytes
Date: Sat, 15 Mar 2025 09:59:57 GMT
Via: 1.1 varnish
X-Served-By: cache-del21729-DEL
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1742032797.192252,VS0,VE541
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 7ba2f4922ed79fcd565e1f98327dc69f0e78892e
Expires: Sat, 15 Mar 2025 10:04:57 GMT
Source-Age: 0

]
[2025-03-15 15:29:55,918:INFO: main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-15 15:29:55,918:INFO: main:>>>>>> stage Data Validation stage started <<<<<<]
[2025-03-15 15:29:55,918:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 15:29:55,932:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 15:29:55,936:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 15:29:55,939:INFO: common:created directory at: artifacts]
[2025-03-15 15:29:55,940:INFO: common:created directory at: artifacts/data_validation]
[2025-03-15 15:29:55,985:INFO: main:>>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-15 15:29:55,987:INFO: main:>>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-15 15:29:55,993:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 15:29:55,994:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 15:29:55,995:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 15:29:55,995:INFO: common:created directory at: artifacts]
[2025-03-15 15:29:55,995:INFO: common:created directory at: artifacts/data_transformation]
[2025-03-15 15:29:56,020:INFO: data_transformation:Splited data into training and test sets]
[2025-03-15 15:29:56,020:INFO: data_transformation:(1199, 12)]
[2025-03-15 15:29:56,020:INFO: data_transformation:(400, 12)]
[2025-03-15 15:29:56,024:INFO: main:>>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-15 15:30:59,068:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 15:30:59,072:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 15:30:59,076:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 15:30:59,078:INFO: common:created directory at: artifacts]
[2025-03-15 15:30:59,081:INFO: common:created directory at: artifacts/model_trainer]
[2025-03-15 15:35:29,364:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 15:35:29,366:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 15:35:29,371:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 15:35:29,371:INFO: common:created directory at: artifacts]
[2025-03-15 15:35:29,376:INFO: common:created directory at: artifacts/model_trainer]
[2025-03-15 15:40:21,203:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 15:40:21,203:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 15:40:21,210:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 15:40:21,213:INFO: common:created directory at: artifacts]
[2025-03-15 15:40:21,215:INFO: common:created directory at: artifacts/model_trainer]
[2025-03-15 15:40:54,865:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 15:40:54,867:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 15:40:54,870:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 15:40:54,874:INFO: common:created directory at: artifacts]
[2025-03-15 15:40:54,874:INFO: common:created directory at: artifacts/model_trainer]
[2025-03-15 15:43:42,128:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 15:43:42,130:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 15:43:42,134:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 15:43:42,137:INFO: common:created directory at: artifacts]
[2025-03-15 15:43:42,138:INFO: common:created directory at: artifacts/model_trainer]
[2025-03-15 15:54:13,387:INFO: main:Welcome to our custom login]
[2025-03-15 15:54:13,387:INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-15 15:54:13,398:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 15:54:13,398:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 15:54:13,401:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 15:54:13,401:INFO: common:created directory at: artifacts]
[2025-03-15 15:54:13,402:INFO: common:created directory at: artifacts/data_ingestion]
[2025-03-15 15:54:14,379:INFO: data_ingestion:artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 26176
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "f751ec0917e15a3dc07c3094a49fb99713109dd8a9f29150bb5d187ec17facdf"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 9EAE:2F9996:6EB14:133469:67D54F9C
Accept-Ranges: bytes
Date: Sat, 15 Mar 2025 10:24:16 GMT
Via: 1.1 varnish
X-Served-By: cache-del21746-DEL
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1742034256.899690,VS0,VE298
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: fa755571aa06a35d9b110aa950855edbf80f7cd8
Expires: Sat, 15 Mar 2025 10:29:16 GMT
Source-Age: 0

]
[2025-03-15 15:54:14,425:INFO: main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-15 15:54:14,425:INFO: main:>>>>>> stage Data Validation stage started <<<<<<]
[2025-03-15 15:54:14,425:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 15:54:14,430:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 15:54:14,433:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 15:54:14,435:INFO: common:created directory at: artifacts]
[2025-03-15 15:54:14,435:INFO: common:created directory at: artifacts/data_validation]
[2025-03-15 15:54:14,488:INFO: main:>>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-15 15:54:14,490:INFO: main:>>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-15 15:54:14,494:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 15:54:14,494:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 15:54:14,497:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 15:54:14,498:INFO: common:created directory at: artifacts]
[2025-03-15 15:54:14,499:INFO: common:created directory at: artifacts/data_transformation]
[2025-03-15 15:54:14,523:INFO: data_transformation:Splited data into training and test sets]
[2025-03-15 15:54:14,523:INFO: data_transformation:(1199, 12)]
[2025-03-15 15:54:14,523:INFO: data_transformation:(400, 12)]
[2025-03-15 15:54:14,527:INFO: main:>>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-15 15:54:14,527:INFO: main:>>>>>> stage Model Trainer stage started <<<<<<]
[2025-03-15 15:54:14,527:ERROR: main:name 'ModelTrainerTrainingPipeline' is not defined]
Traceback (most recent call last):
  File "d:\KC\End to End MLflow\main.py", line 44, in <module>
    data_ingestion = ModelTrainerTrainingPipeline()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'ModelTrainerTrainingPipeline' is not defined
[2025-03-15 23:56:08,482:INFO: main:Welcome to our custom login]
[2025-03-15 23:56:08,482:INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-15 23:56:08,483:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 23:56:08,485:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 23:56:08,486:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 23:56:08,487:INFO: common:created directory at: artifacts]
[2025-03-15 23:56:08,487:INFO: common:created directory at: artifacts/data_ingestion]
[2025-03-15 23:56:08,487:INFO: data_ingestion:File already exists of size: ~ 26 KB]
[2025-03-15 23:56:08,492:INFO: main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-15 23:56:08,492:INFO: main:>>>>>> stage Data Validation stage started <<<<<<]
[2025-03-15 23:56:08,495:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 23:56:08,496:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 23:56:08,497:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 23:56:08,500:INFO: common:created directory at: artifacts]
[2025-03-15 23:56:08,500:INFO: common:created directory at: artifacts/data_validation]
[2025-03-15 23:56:08,587:INFO: main:>>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-15 23:56:08,589:INFO: main:>>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-15 23:56:08,593:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 23:56:08,595:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 23:56:08,599:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 23:56:08,602:INFO: common:created directory at: artifacts]
[2025-03-15 23:56:08,602:INFO: common:created directory at: artifacts/data_transformation]
[2025-03-15 23:56:08,620:INFO: data_transformation:Splited data into training and test sets]
[2025-03-15 23:56:08,623:INFO: data_transformation:(1199, 12)]
[2025-03-15 23:56:08,623:INFO: data_transformation:(400, 12)]
[2025-03-15 23:56:08,624:INFO: main:>>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-15 23:56:08,625:INFO: main:>>>>>> stage Model Trainer stage started <<<<<<]
[2025-03-15 23:56:08,626:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 23:56:08,627:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 23:56:08,629:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 23:56:08,629:INFO: common:created directory at: artifacts]
[2025-03-15 23:56:08,630:ERROR: main:'ConfigurationManager' object has no attribute 'get_model_trainer_config']
Traceback (most recent call last):
  File "d:\KC\End to End MLflow\main.py", line 46, in <module>
    data_ingestion.main()
  File "d:\kc\end to end mlflow\src\mlproject\pipeline\stage04_model_training.py", line 15, in main
    model_trainer_config = config.get_model_trainer_config()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigurationManager' object has no attribute 'get_model_trainer_config'
[2025-03-15 23:57:28,191:INFO: main:Welcome to our custom login]
[2025-03-15 23:57:28,192:INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-15 23:57:28,193:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 23:57:28,196:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 23:57:28,197:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 23:57:28,198:INFO: common:created directory at: artifacts]
[2025-03-15 23:57:28,198:INFO: common:created directory at: artifacts/data_ingestion]
[2025-03-15 23:57:28,199:INFO: data_ingestion:File already exists of size: ~ 26 KB]
[2025-03-15 23:57:28,201:INFO: main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-15 23:57:28,201:INFO: main:>>>>>> stage Data Validation stage started <<<<<<]
[2025-03-15 23:57:28,203:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 23:57:28,204:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 23:57:28,205:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 23:57:28,206:INFO: common:created directory at: artifacts]
[2025-03-15 23:57:28,207:INFO: common:created directory at: artifacts/data_validation]
[2025-03-15 23:57:28,242:INFO: main:>>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-15 23:57:28,242:INFO: main:>>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-15 23:57:28,246:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 23:57:28,248:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 23:57:28,250:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 23:57:28,251:INFO: common:created directory at: artifacts]
[2025-03-15 23:57:28,252:INFO: common:created directory at: artifacts/data_transformation]
[2025-03-15 23:57:28,258:INFO: data_transformation:Splited data into training and test sets]
[2025-03-15 23:57:28,258:INFO: data_transformation:(1199, 12)]
[2025-03-15 23:57:28,258:INFO: data_transformation:(400, 12)]
[2025-03-15 23:57:28,270:INFO: main:>>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-15 23:57:28,270:INFO: main:>>>>>> stage Model Trainer stage started <<<<<<]
[2025-03-15 23:57:28,272:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-15 23:57:28,273:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-15 23:57:28,275:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-15 23:57:28,276:INFO: common:created directory at: artifacts]
[2025-03-15 23:57:28,276:ERROR: main:'ConfigurationManager' object has no attribute 'get_model_training_config']
Traceback (most recent call last):
  File "d:\KC\End to End MLflow\main.py", line 46, in <module>
    data_ingestion.main()
  File "d:\kc\end to end mlflow\src\mlproject\pipeline\stage04_model_training.py", line 15, in main
    model_trainer_config = config.get_model_training_config()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigurationManager' object has no attribute 'get_model_training_config'
[2025-03-16 00:00:13,627:INFO: main:Welcome to our custom login]
[2025-03-16 00:00:13,627:INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-16 00:00:13,629:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-16 00:00:13,630:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-16 00:00:13,631:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-16 00:00:13,632:INFO: common:created directory at: artifacts]
[2025-03-16 00:00:13,632:INFO: common:created directory at: artifacts/data_ingestion]
[2025-03-16 00:00:13,633:INFO: data_ingestion:File already exists of size: ~ 26 KB]
[2025-03-16 00:00:13,635:INFO: main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-16 00:00:13,635:INFO: main:>>>>>> stage Data Validation stage started <<<<<<]
[2025-03-16 00:00:13,637:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-16 00:00:13,639:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-16 00:00:13,640:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-16 00:00:13,641:INFO: common:created directory at: artifacts]
[2025-03-16 00:00:13,641:INFO: common:created directory at: artifacts/data_validation]
[2025-03-16 00:00:13,673:INFO: main:>>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-16 00:00:13,673:INFO: main:>>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-16 00:00:13,680:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-16 00:00:13,681:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-16 00:00:13,682:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-16 00:00:13,683:INFO: common:created directory at: artifacts]
[2025-03-16 00:00:13,684:INFO: common:created directory at: artifacts/data_transformation]
[2025-03-16 00:00:13,696:INFO: data_transformation:Splited data into training and test sets]
[2025-03-16 00:00:13,696:INFO: data_transformation:(1199, 12)]
[2025-03-16 00:00:13,696:INFO: data_transformation:(400, 12)]
[2025-03-16 00:00:13,703:INFO: main:>>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-16 00:00:13,704:INFO: main:>>>>>> stage Model Trainer stage started <<<<<<]
[2025-03-16 00:00:13,706:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-16 00:00:13,708:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-16 00:00:13,709:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-16 00:00:13,711:INFO: common:created directory at: artifacts]
[2025-03-16 00:00:13,712:INFO: common:created directory at: artifacts/model_trainer]
[2025-03-16 00:00:13,747:INFO: main:>>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2025-03-17 12:57:26,484:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-17 12:57:26,495:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-17 12:57:26,509:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-17 12:57:26,511:INFO: common:created directory at: artifacts]
[2025-03-17 12:57:26,511:INFO: common:created directory at: artifacts]
[2025-03-17 13:01:48,548:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-17 13:01:48,548:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-17 13:01:48,552:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-17 13:01:48,554:INFO: common:created directory at: artifacts]
[2025-03-17 13:01:48,554:INFO: common:created directory at: artifacts]
[2025-03-17 13:28:55,660:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-17 13:28:55,663:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-17 13:28:55,666:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-17 13:28:55,667:INFO: common:created directory at: artifacts]
[2025-03-17 13:28:55,668:INFO: common:created directory at: artifacts]
[2025-03-17 13:31:53,317:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-17 13:31:53,321:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-17 13:31:53,324:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-17 13:31:53,324:INFO: common:created directory at: artifacts]
[2025-03-17 13:31:53,324:INFO: common:created directory at: artifacts]
[2025-03-17 13:39:06,360:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-17 13:39:06,363:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-17 13:39:06,370:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-17 13:39:06,370:INFO: common:created directory at: artifacts]
[2025-03-17 13:39:06,370:INFO: common:created directory at: artifacts]
[2025-03-17 13:39:06,370:INFO: common:created directory at: artifacts/model_evaluation]
[2025-03-17 13:39:06,865:INFO: common:json file saved at: artifacts\model_evaluation\metrics.json]
[2025-03-18 00:21:26,941:INFO: main:Welcome to our custom login]
[2025-03-18 00:21:26,941:INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-18 00:21:26,941:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 00:21:26,941:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 00:21:26,954:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 00:21:26,963:INFO: common:created directory at: artifacts]
[2025-03-18 00:21:26,991:INFO: common:created directory at: artifacts/data_ingestion]
[2025-03-18 00:21:27,730:ERROR: main:HTTP Error 404: Not Found]
Traceback (most recent call last):
  File "d:\KC\End to End MLflow\main.py", line 16, in <module>
    data_ingestion.main()
  File "d:\kc\end to end mlflow\src\mlproject\pipeline\stage01_data_ingestion.py", line 17, in main
    data_ingestion.download_file()
  File "d:\kc\end to end mlflow\src\mlproject\components\data_ingestion.py", line 16, in download_file
    filename, headers = request.urlretrieve(
                        ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2025-03-18 00:36:38,711:INFO: main:Welcome to our custom login]
[2025-03-18 00:36:38,711:INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-18 00:36:38,714:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 00:36:38,716:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 00:36:38,717:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 00:36:38,717:INFO: common:created directory at: artifacts]
[2025-03-18 00:36:38,719:INFO: common:created directory at: artifacts/data_ingestion]
[2025-03-18 00:36:39,437:ERROR: main:HTTP Error 404: Not Found]
Traceback (most recent call last):
  File "d:\KC\End to End MLflow\main.py", line 16, in <module>
    data_ingestion.main()
  File "d:\kc\end to end mlflow\src\mlproject\pipeline\stage01_data_ingestion.py", line 17, in main
    data_ingestion.download_file()
  File "d:\kc\end to end mlflow\src\mlproject\components\data_ingestion.py", line 16, in download_file
    filename, headers = request.urlretrieve(
                        ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2025-03-18 00:47:08,216:INFO: main:Welcome to our custom login]
[2025-03-18 00:47:08,216:INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-18 00:47:08,216:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 00:47:08,232:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 00:47:08,250:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 00:47:08,250:INFO: common:created directory at: artifacts]
[2025-03-18 00:47:08,252:INFO: common:created directory at: artifacts/data_ingestion]
[2025-03-18 00:47:09,034:ERROR: main:HTTP Error 404: Not Found]
Traceback (most recent call last):
  File "d:\KC\End to End MLflow\main.py", line 16, in <module>
    data_ingestion.main()
  File "d:\kc\end to end mlflow\src\mlproject\pipeline\stage01_data_ingestion.py", line 17, in main
    data_ingestion.download_file()
  File "d:\kc\end to end mlflow\src\mlproject\components\data_ingestion.py", line 16, in download_file
    filename, headers = request.urlretrieve(
                        ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2025-03-18 00:49:11,456:INFO: main:Welcome to our custom login]
[2025-03-18 00:49:11,456:INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-18 00:49:11,456:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 00:49:11,456:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 00:49:11,472:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 00:49:11,473:INFO: common:created directory at: artifacts]
[2025-03-18 00:49:11,473:INFO: common:created directory at: artifacts/data_ingestion]
[2025-03-18 00:49:12,260:ERROR: main:HTTP Error 404: Not Found]
Traceback (most recent call last):
  File "d:\KC\End to End MLflow\main.py", line 16, in <module>
    data_ingestion.main()
  File "d:\kc\end to end mlflow\src\mlproject\pipeline\stage01_data_ingestion.py", line 17, in main
    data_ingestion.download_file()
  File "d:\kc\end to end mlflow\src\mlproject\components\data_ingestion.py", line 16, in download_file
    filename, headers = request.urlretrieve(
                        ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2025-03-18 00:54:04,364:INFO: main:Welcome to our custom login]
[2025-03-18 00:54:04,364:INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-18 00:54:04,364:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 00:54:04,364:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 00:54:04,372:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 00:54:04,374:INFO: common:created directory at: artifacts]
[2025-03-18 00:54:04,375:INFO: common:created directory at: artifacts/data_ingestion]
[2025-03-18 00:54:05,084:ERROR: main:HTTP Error 404: Not Found]
Traceback (most recent call last):
  File "d:\KC\End to End MLflow\main.py", line 16, in <module>
    data_ingestion.main()
  File "d:\kc\end to end mlflow\src\mlproject\pipeline\stage01_data_ingestion.py", line 17, in main
    data_ingestion.download_file()
  File "d:\kc\end to end mlflow\src\mlproject\components\data_ingestion.py", line 16, in download_file
    filename, headers = request.urlretrieve(
                        ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2025-03-18 10:09:51,176:INFO: main:Welcome to our custom login]
[2025-03-18 10:09:51,177:INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-18 10:09:51,178:ERROR: main:while scanning a simple key
  in "config\config.yaml", line 5, column 3
could not find expected ':'
  in "config\config.yaml", line 6, column 3]
Traceback (most recent call last):
  File "d:\KC\End to End MLflow\main.py", line 16, in <module>
    data_ingestion.main()
  File "d:\kc\end to end mlflow\src\mlproject\pipeline\stage01_data_ingestion.py", line 14, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "d:\kc\end to end mlflow\src\mlproject\config\configuration.py", line 16, in __init__
    self.config = read_yaml(config_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\kc\end to end mlflow\src\mlproject\utils\common.py", line 36, in read_yaml
    raise e
  File "d:\kc\end to end mlflow\src\mlproject\utils\common.py", line 30, in read_yaml
    content = yaml.safe_load(yaml_file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\scanner.py", line 115, in check_token
    while self.need_more_tokens():
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\yaml\scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "config\config.yaml", line 5, column 3
could not find expected ':'
  in "config\config.yaml", line 6, column 3
[2025-03-18 10:23:00,281:INFO: main:Welcome to our custom login]
[2025-03-18 10:23:00,281:INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-18 10:23:00,303:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 10:23:00,303:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 10:23:00,313:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 10:23:00,313:INFO: common:created directory at: artifacts]
[2025-03-18 10:23:00,313:INFO: common:created directory at: artifacts/data_ingestion]
[2025-03-18 10:23:00,981:INFO: data_ingestion:artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 26176
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "f751ec0917e15a3dc07c3094a49fb99713109dd8a9f29150bb5d187ec17facdf"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 187C:23CBE2:3B198B:9FEFA2:67D8FB8C
Accept-Ranges: bytes
Date: Tue, 18 Mar 2025 04:53:01 GMT
Via: 1.1 varnish
X-Served-By: cache-del21741-DEL
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1742273581.237496,VS0,VE1
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: d800db7e5d2844f09344c40bcd7de24feea89b0b
Expires: Tue, 18 Mar 2025 04:58:01 GMT
Source-Age: 160

]
[2025-03-18 10:23:00,999:INFO: main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-18 10:23:00,999:INFO: main:>>>>>> stage Data Validation stage started <<<<<<]
[2025-03-18 10:23:01,004:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 10:23:01,004:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 10:23:01,004:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 10:23:01,004:INFO: common:created directory at: artifacts]
[2025-03-18 10:23:01,010:INFO: common:created directory at: artifacts/data_validation]
[2025-03-18 10:23:01,066:INFO: main:>>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-18 10:23:01,066:INFO: main:>>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-18 10:23:01,081:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 10:23:01,081:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 10:23:01,081:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 10:23:01,081:INFO: common:created directory at: artifacts]
[2025-03-18 10:23:01,088:INFO: common:created directory at: artifacts/data_transformation]
[2025-03-18 10:23:01,108:INFO: data_transformation:Splited data into training and test sets]
[2025-03-18 10:23:01,108:INFO: data_transformation:(1199, 12)]
[2025-03-18 10:23:01,108:INFO: data_transformation:(400, 12)]
[2025-03-18 10:23:01,108:INFO: main:>>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-18 10:23:01,114:INFO: main:>>>>>> stage Model Trainer stage started <<<<<<]
[2025-03-18 10:23:01,118:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 10:23:01,119:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 10:23:01,121:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 10:23:01,123:INFO: common:created directory at: artifacts]
[2025-03-18 10:23:01,123:INFO: common:created directory at: artifacts/model_trainer]
[2025-03-18 10:23:01,204:INFO: main:>>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2025-03-18 10:29:49,018:INFO: main:Welcome to our custom login]
[2025-03-18 10:29:49,018:INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-18 10:29:49,025:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 10:29:49,026:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 10:29:49,026:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 10:29:49,026:INFO: common:created directory at: artifacts]
[2025-03-18 10:29:49,029:INFO: common:created directory at: artifacts/data_ingestion]
[2025-03-18 10:29:49,914:INFO: data_ingestion:artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 26176
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "f751ec0917e15a3dc07c3094a49fb99713109dd8a9f29150bb5d187ec17facdf"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 187C:23CBE2:3B198B:9FEFA2:67D8FB8C
Accept-Ranges: bytes
Date: Tue, 18 Mar 2025 04:59:50 GMT
Via: 1.1 varnish
X-Served-By: cache-del21747-DEL
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1742273990.891584,VS0,VE266
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 6fd9f7f087d4d2f5b16d52089d1b2d170c0dd2f8
Expires: Tue, 18 Mar 2025 05:04:50 GMT
Source-Age: 0

]
[2025-03-18 10:29:49,940:INFO: main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-18 10:29:49,940:INFO: main:>>>>>> stage Data Validation stage started <<<<<<]
[2025-03-18 10:29:49,942:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 10:29:49,942:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 10:29:49,944:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 10:29:49,944:INFO: common:created directory at: artifacts]
[2025-03-18 10:29:49,949:INFO: common:created directory at: artifacts/data_validation]
[2025-03-18 10:29:49,985:INFO: main:>>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-18 10:29:49,985:INFO: main:>>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-18 10:29:49,988:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 10:29:49,991:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 10:29:49,994:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 10:29:49,994:INFO: common:created directory at: artifacts]
[2025-03-18 10:29:49,995:INFO: common:created directory at: artifacts/data_transformation]
[2025-03-18 10:29:50,015:INFO: data_transformation:Splited data into training and test sets]
[2025-03-18 10:29:50,015:INFO: data_transformation:(1199, 12)]
[2025-03-18 10:29:50,015:INFO: data_transformation:(400, 12)]
[2025-03-18 10:29:50,015:INFO: main:>>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-18 10:29:50,015:INFO: main:>>>>>> stage Model Trainer stage started <<<<<<]
[2025-03-18 10:29:50,015:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 10:29:50,015:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 10:29:50,023:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 10:29:50,023:INFO: common:created directory at: artifacts]
[2025-03-18 10:29:50,023:INFO: common:created directory at: artifacts/model_trainer]
[2025-03-18 10:29:50,080:INFO: main:>>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2025-03-18 10:29:50,080:INFO: main:>>>>>> stage Model evaluation stage started <<<<<<]
[2025-03-18 10:29:50,080:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 10:29:50,080:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 10:29:50,080:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 10:29:50,080:INFO: common:created directory at: artifacts]
[2025-03-18 10:29:50,080:ERROR: main:'ConfigurationManager' object has no attribute 'get_model_evaluation_config']
Traceback (most recent call last):
  File "d:\KC\End to End MLflow\main.py", line 57, in <module>
    data_ingestion.main()
  File "d:\kc\end to end mlflow\src\mlproject\pipeline\stage05_model_evaluation.py", line 13, in main
    model_evaluation_config = config.get_model_evaluation_config()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigurationManager' object has no attribute 'get_model_evaluation_config'. Did you mean: 'get_data_validation_config'?
[2025-03-18 10:31:32,025:INFO: main:Welcome to our custom login]
[2025-03-18 10:31:32,025:INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-18 10:31:32,041:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 10:31:32,041:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 10:31:32,041:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 10:31:32,041:INFO: common:created directory at: artifacts]
[2025-03-18 10:31:32,041:INFO: common:created directory at: artifacts/data_ingestion]
[2025-03-18 10:31:32,041:INFO: data_ingestion:File already exists of size: ~ 26 KB]
[2025-03-18 10:31:32,041:INFO: main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-18 10:31:32,041:INFO: main:>>>>>> stage Data Validation stage started <<<<<<]
[2025-03-18 10:31:32,055:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 10:31:32,055:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 10:31:32,059:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 10:31:32,059:INFO: common:created directory at: artifacts]
[2025-03-18 10:31:32,059:INFO: common:created directory at: artifacts/data_validation]
[2025-03-18 10:31:32,103:INFO: main:>>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-18 10:31:32,103:INFO: main:>>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-18 10:31:32,103:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 10:31:32,109:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 10:31:32,110:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 10:31:32,111:INFO: common:created directory at: artifacts]
[2025-03-18 10:31:32,111:INFO: common:created directory at: artifacts/data_transformation]
[2025-03-18 10:31:32,131:INFO: data_transformation:Splited data into training and test sets]
[2025-03-18 10:31:32,131:INFO: data_transformation:(1199, 12)]
[2025-03-18 10:31:32,131:INFO: data_transformation:(400, 12)]
[2025-03-18 10:31:32,131:INFO: main:>>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-18 10:31:32,131:INFO: main:>>>>>> stage Model Trainer stage started <<<<<<]
[2025-03-18 10:31:32,133:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 10:31:32,133:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 10:31:32,133:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 10:31:32,133:INFO: common:created directory at: artifacts]
[2025-03-18 10:31:32,133:INFO: common:created directory at: artifacts/model_trainer]
[2025-03-18 10:31:32,189:INFO: main:>>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2025-03-18 10:31:32,189:INFO: main:>>>>>> stage Model evaluation stage started <<<<<<]
[2025-03-18 10:31:32,189:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 10:31:32,189:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 10:31:32,189:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 10:31:32,198:INFO: common:created directory at: artifacts]
[2025-03-18 10:31:32,200:INFO: common:created directory at: artifacts]
[2025-03-18 10:31:32,201:INFO: common:created directory at: artifacts/model_evaluation]
[2025-03-18 10:31:33,495:ERROR: main:API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "d:\KC\End to End MLflow\main.py", line 57, in <module>
    data_ingestion.main()
  File "d:\kc\end to end mlflow\src\mlproject\pipeline\stage05_model_evaluation.py", line 15, in main
    model_evaluation_config.log_into_mlflow()
  File "d:\kc\end to end mlflow\src\mlproject\components\model_evaluation.py", line 40, in log_into_mlflow
    with mlflow.start_run():
         ^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\mlflow\tracking\fluent.py", line 446, in start_run
    active_run_obj = client.create_run(
                     ^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\mlflow\tracking\client.py", line 418, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 170, in create_run
    return self.store.create_run(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 220, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 90, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\mlflow\utils\rest_utils.py", line 392, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\mlflow\utils\rest_utils.py", line 255, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2025-03-18 10:34:05,380:INFO: main:Welcome to our custom login]
[2025-03-18 10:34:05,380:INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-18 10:34:05,380:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 10:34:05,380:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 10:34:05,380:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 10:34:05,380:INFO: common:created directory at: artifacts]
[2025-03-18 10:34:05,388:INFO: common:created directory at: artifacts/data_ingestion]
[2025-03-18 10:34:05,388:INFO: data_ingestion:File already exists of size: ~ 26 KB]
[2025-03-18 10:34:05,393:INFO: main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-18 10:34:05,393:INFO: main:>>>>>> stage Data Validation stage started <<<<<<]
[2025-03-18 10:34:05,399:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 10:34:05,401:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 10:34:05,401:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 10:34:05,403:INFO: common:created directory at: artifacts]
[2025-03-18 10:34:05,404:INFO: common:created directory at: artifacts/data_validation]
[2025-03-18 10:34:05,459:INFO: main:>>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-18 10:34:05,459:INFO: main:>>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-18 10:34:05,459:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 10:34:05,467:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 10:34:05,468:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 10:34:05,470:INFO: common:created directory at: artifacts]
[2025-03-18 10:34:05,470:INFO: common:created directory at: artifacts/data_transformation]
[2025-03-18 10:34:05,492:INFO: data_transformation:Splited data into training and test sets]
[2025-03-18 10:34:05,492:INFO: data_transformation:(1199, 12)]
[2025-03-18 10:34:05,492:INFO: data_transformation:(400, 12)]
[2025-03-18 10:34:05,492:INFO: main:>>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-18 10:34:05,492:INFO: main:>>>>>> stage Model Trainer stage started <<<<<<]
[2025-03-18 10:34:05,492:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 10:34:05,492:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 10:34:05,492:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 10:34:05,492:INFO: common:created directory at: artifacts]
[2025-03-18 10:34:05,492:INFO: common:created directory at: artifacts/model_trainer]
[2025-03-18 10:34:05,555:INFO: main:>>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2025-03-18 10:34:05,555:INFO: main:>>>>>> stage Model evaluation stage started <<<<<<]
[2025-03-18 10:34:05,555:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 10:34:05,555:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 10:34:05,566:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 10:34:05,567:INFO: common:created directory at: artifacts]
[2025-03-18 10:34:05,568:INFO: common:created directory at: artifacts]
[2025-03-18 10:34:05,568:INFO: common:created directory at: artifacts/model_evaluation]
[2025-03-18 10:34:06,740:ERROR: main:API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "d:\KC\End to End MLflow\main.py", line 57, in <module>
    data_ingestion.main()
  File "d:\kc\end to end mlflow\src\mlproject\pipeline\stage05_model_evaluation.py", line 15, in main
    model_evaluation_config.log_into_mlflow()
  File "d:\kc\end to end mlflow\src\mlproject\components\model_evaluation.py", line 40, in log_into_mlflow
    with mlflow.start_run():
         ^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\mlflow\tracking\fluent.py", line 446, in start_run
    active_run_obj = client.create_run(
                     ^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\mlflow\tracking\client.py", line 418, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 170, in create_run
    return self.store.create_run(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 220, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 90, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\mlflow\utils\rest_utils.py", line 392, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\mlflow\utils\rest_utils.py", line 255, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2025-03-18 10:36:10,724:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 10:36:10,729:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 10:36:10,733:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 10:36:10,735:INFO: common:created directory at: artifacts]
[2025-03-18 10:36:10,740:INFO: common:created directory at: artifacts]
[2025-03-18 10:36:10,741:INFO: common:created directory at: artifacts/model_evaluation]
[2025-03-18 10:36:11,919:INFO: common:json file saved at: artifacts\model_evaluation\metrics.json]
[2025-03-18 10:56:01,432:INFO: main:Welcome to our custom login]
[2025-03-18 10:56:01,432:INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-18 10:56:01,476:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 10:56:01,479:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 10:56:01,479:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 10:56:01,479:INFO: common:created directory at: artifacts]
[2025-03-18 10:56:01,479:INFO: common:created directory at: artifacts/data_ingestion]
[2025-03-18 10:56:01,479:INFO: data_ingestion:File already exists of size: ~ 26 KB]
[2025-03-18 10:56:01,479:INFO: main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-18 10:56:01,479:INFO: main:>>>>>> stage Data Validation stage started <<<<<<]
[2025-03-18 10:56:01,488:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 10:56:01,488:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 10:56:01,488:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 10:56:01,488:INFO: common:created directory at: artifacts]
[2025-03-18 10:56:01,488:INFO: common:created directory at: artifacts/data_validation]
[2025-03-18 10:56:01,546:INFO: main:>>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-18 10:56:01,546:INFO: main:>>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-18 10:56:01,563:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 10:56:01,566:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 10:56:01,566:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 10:56:01,566:INFO: common:created directory at: artifacts]
[2025-03-18 10:56:01,566:INFO: common:created directory at: artifacts/data_transformation]
[2025-03-18 10:56:01,592:INFO: data_transformation:Splited data into training and test sets]
[2025-03-18 10:56:01,592:INFO: data_transformation:(1199, 12)]
[2025-03-18 10:56:01,592:INFO: data_transformation:(400, 12)]
[2025-03-18 10:56:01,592:INFO: main:>>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-18 10:56:01,592:INFO: main:>>>>>> stage Model Trainer stage started <<<<<<]
[2025-03-18 10:56:01,592:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 10:56:01,592:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 10:56:01,592:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 10:56:01,592:INFO: common:created directory at: artifacts]
[2025-03-18 10:56:01,592:INFO: common:created directory at: artifacts/model_trainer]
[2025-03-18 10:56:01,657:INFO: main:>>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2025-03-18 10:56:01,657:INFO: main:>>>>>> stage Model evaluation stage started <<<<<<]
[2025-03-18 10:56:01,657:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 10:56:01,670:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 10:56:01,674:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 10:56:01,674:INFO: common:created directory at: artifacts]
[2025-03-18 10:56:01,674:INFO: common:created directory at: artifacts]
[2025-03-18 10:56:01,674:INFO: common:created directory at: artifacts/model_evaluation]
[2025-03-18 10:56:03,120:ERROR: main:API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "d:\KC\End to End MLflow\main.py", line 57, in <module>
    data_ingestion.main()
  File "d:\kc\end to end mlflow\src\mlproject\pipeline\stage05_model_evaluation.py", line 15, in main
    model_evaluation_config.log_into_mlflow()
  File "d:\kc\end to end mlflow\src\mlproject\components\model_evaluation.py", line 39, in log_into_mlflow
    with mlflow.start_run():
         ^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\mlflow\tracking\fluent.py", line 446, in start_run
    active_run_obj = client.create_run(
                     ^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\mlflow\tracking\client.py", line 418, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 170, in create_run
    return self.store.create_run(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 220, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 90, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\mlflow\utils\rest_utils.py", line 392, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\mlflow\utils\rest_utils.py", line 255, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2025-03-18 10:57:14,767:INFO: main:Welcome to our custom login]
[2025-03-18 10:57:14,774:INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-18 10:57:14,774:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 10:57:14,774:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 10:57:14,774:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 10:57:14,774:INFO: common:created directory at: artifacts]
[2025-03-18 10:57:14,774:INFO: common:created directory at: artifacts/data_ingestion]
[2025-03-18 10:57:14,781:INFO: data_ingestion:File already exists of size: ~ 26 KB]
[2025-03-18 10:57:14,784:INFO: main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-18 10:57:14,784:INFO: main:>>>>>> stage Data Validation stage started <<<<<<]
[2025-03-18 10:57:14,790:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 10:57:14,793:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 10:57:14,793:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 10:57:14,793:INFO: common:created directory at: artifacts]
[2025-03-18 10:57:14,793:INFO: common:created directory at: artifacts/data_validation]
[2025-03-18 10:57:14,859:INFO: main:>>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-18 10:57:14,859:INFO: main:>>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-18 10:57:14,867:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 10:57:14,869:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 10:57:14,872:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 10:57:14,873:INFO: common:created directory at: artifacts]
[2025-03-18 10:57:14,873:INFO: common:created directory at: artifacts/data_transformation]
[2025-03-18 10:57:14,894:INFO: data_transformation:Splited data into training and test sets]
[2025-03-18 10:57:14,894:INFO: data_transformation:(1199, 12)]
[2025-03-18 10:57:14,900:INFO: data_transformation:(400, 12)]
[2025-03-18 10:57:14,901:INFO: main:>>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-18 10:57:14,901:INFO: main:>>>>>> stage Model Trainer stage started <<<<<<]
[2025-03-18 10:57:14,901:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 10:57:14,906:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 10:57:14,909:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 10:57:14,909:INFO: common:created directory at: artifacts]
[2025-03-18 10:57:14,909:INFO: common:created directory at: artifacts/model_trainer]
[2025-03-18 10:57:14,968:INFO: main:>>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2025-03-18 10:57:14,968:INFO: main:>>>>>> stage Model evaluation stage started <<<<<<]
[2025-03-18 10:57:14,971:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 10:57:14,971:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 10:57:14,977:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 10:57:14,980:INFO: common:created directory at: artifacts]
[2025-03-18 10:57:14,980:INFO: common:created directory at: artifacts]
[2025-03-18 10:57:14,980:INFO: common:created directory at: artifacts/model_evaluation]
[2025-03-18 10:57:16,392:ERROR: main:API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "d:\KC\End to End MLflow\main.py", line 57, in <module>
    data_ingestion.main()
  File "d:\kc\end to end mlflow\src\mlproject\pipeline\stage05_model_evaluation.py", line 15, in main
    model_evaluation_config.log_into_mlflow()
  File "d:\kc\end to end mlflow\src\mlproject\components\model_evaluation.py", line 39, in log_into_mlflow
    with mlflow.start_run():
         ^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\mlflow\tracking\fluent.py", line 446, in start_run
    active_run_obj = client.create_run(
                     ^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\mlflow\tracking\client.py", line 418, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 170, in create_run
    return self.store.create_run(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 220, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 90, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\mlflow\utils\rest_utils.py", line 392, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\KC\End to End MLflow\.venv\Lib\site-packages\mlflow\utils\rest_utils.py", line 255, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2025-03-18 11:11:46,071:INFO: main:Welcome to our custom login]
[2025-03-18 11:11:46,071:INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-18 11:11:46,075:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 11:11:46,084:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 11:11:46,091:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 11:11:46,092:INFO: common:created directory at: artifacts]
[2025-03-18 11:11:46,092:INFO: common:created directory at: artifacts/data_ingestion]
[2025-03-18 11:11:47,084:INFO: data_ingestion:artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 26176
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "f751ec0917e15a3dc07c3094a49fb99713109dd8a9f29150bb5d187ec17facdf"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 187C:23CBE2:3B198B:9FEFA2:67D8FB8C
Accept-Ranges: bytes
Date: Tue, 18 Mar 2025 05:41:47 GMT
Via: 1.1 varnish
X-Served-By: cache-del21723-DEL
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1742276507.019127,VS0,VE317
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 0ca8595a3d50f843b45890abf2d1cb2a64349308
Expires: Tue, 18 Mar 2025 05:46:47 GMT
Source-Age: 0

]
[2025-03-18 11:11:47,106:INFO: main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-18 11:11:47,106:INFO: main:>>>>>> stage Data Validation stage started <<<<<<]
[2025-03-18 11:11:47,110:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 11:11:47,112:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 11:11:47,114:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 11:11:47,115:INFO: common:created directory at: artifacts]
[2025-03-18 11:11:47,116:INFO: common:created directory at: artifacts/data_validation]
[2025-03-18 11:11:47,144:INFO: main:>>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-18 11:11:47,144:INFO: main:>>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-18 11:11:47,148:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 11:11:47,148:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 11:11:47,152:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 11:11:47,153:INFO: common:created directory at: artifacts]
[2025-03-18 11:11:47,154:INFO: common:created directory at: artifacts/data_transformation]
[2025-03-18 11:11:47,165:INFO: data_transformation:Splited data into training and test sets]
[2025-03-18 11:11:47,165:INFO: data_transformation:(1199, 12)]
[2025-03-18 11:11:47,165:INFO: data_transformation:(400, 12)]
[2025-03-18 11:11:47,165:INFO: main:>>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-18 11:11:47,165:INFO: main:>>>>>> stage Model Trainer stage started <<<<<<]
[2025-03-18 11:11:47,165:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 11:11:47,165:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 11:11:47,179:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 11:11:47,180:INFO: common:created directory at: artifacts]
[2025-03-18 11:11:47,181:INFO: common:created directory at: artifacts/model_trainer]
[2025-03-18 11:11:47,220:INFO: main:>>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2025-03-18 11:11:47,220:INFO: main:>>>>>> stage Model evaluation stage started <<<<<<]
[2025-03-18 11:11:47,220:INFO: common:yaml file: config\config.yaml loaded successfully]
[2025-03-18 11:11:47,220:INFO: common:yaml file: params.yaml loaded successfully]
[2025-03-18 11:11:47,220:INFO: common:yaml file: schema.yaml loaded successfully]
[2025-03-18 11:11:47,220:INFO: common:created directory at: artifacts]
[2025-03-18 11:11:47,220:INFO: common:created directory at: artifacts]
[2025-03-18 11:11:47,227:INFO: common:created directory at: artifacts/model_evaluation]
[2025-03-18 11:11:48,362:INFO: common:json file saved at: artifacts\model_evaluation\metrics.json]
[2025-03-18 11:12:02,570:INFO: main:>>>>>> stage Model evaluation stage completed <<<<<<

x==========x]
[2025-03-18 11:55:25,581:INFO: _internal:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.36:8080]
[2025-03-18 11:55:25,581:INFO: _internal:[33mPress CTRL+C to quit[0m]
[2025-03-18 11:55:32,186:INFO: _internal:127.0.0.1 - - [18/Mar/2025 11:55:32] "GET / HTTP/1.1" 200 -]
[2025-03-18 11:55:32,249:INFO: _internal:127.0.0.1 - - [18/Mar/2025 11:55:32] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2025-03-18 11:56:16,383:INFO: _internal:127.0.0.1 - - [18/Mar/2025 11:56:16] "POST /predict HTTP/1.1" 200 -]
[2025-03-18 11:59:20,623:INFO: _internal:127.0.0.1 - - [18/Mar/2025 11:59:20] "POST /predict HTTP/1.1" 200 -]
[2025-03-18 12:09:41,157:INFO: _internal:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.36:8080]
[2025-03-18 12:09:41,157:INFO: _internal:[33mPress CTRL+C to quit[0m]
[2025-03-18 12:09:46,199:INFO: _internal:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.36:8080]
[2025-03-18 12:09:46,199:INFO: _internal:[33mPress CTRL+C to quit[0m]
[2025-03-18 12:10:09,401:INFO: _internal:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.36:8080]
[2025-03-18 12:10:09,406:INFO: _internal:[33mPress CTRL+C to quit[0m]
[2025-03-18 12:10:23,313:INFO: _internal:127.0.0.1 - - [18/Mar/2025 12:10:23] "GET / HTTP/1.1" 200 -]
[2025-03-18 12:10:23,388:INFO: _internal:127.0.0.1 - - [18/Mar/2025 12:10:23] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2025-03-18 12:11:33,658:INFO: _internal:127.0.0.1 - - [18/Mar/2025 12:11:33] "POST /predict HTTP/1.1" 200 -]
